import{S as a}from"./assets/vendor-D4SFNjM9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const e of n)if(e.type==="childList")for(const t of e.addedNodes)t.tagName==="LINK"&&t.rel==="modulepreload"&&r(t)}).observe(document,{childList:!0,subtree:!0});function o(n){const e={};return n.integrity&&(e.integrity=n.integrity),n.referrerPolicy&&(e.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?e.credentials="include":n.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(n){if(n.ep)return;n.ep=!0;const e=o(n);fetch(n.href,e)}})();document.addEventListener("DOMContentLoaded",()=>{new Accordion(".accordion-container",{duration:300,showMultiple:!1,elementClass:"ac",triggerClass:"ac-trigger",panelClass:"ac-panel",activeClass:"is-active",onOpen:s=>{const o=s.querySelector(".ac-panel");o&&(o.style.maxHeight=o.scrollHeight+"px",o.style.overflow="visible")},onClose:s=>{const o=s.querySelector(".ac-panel");o&&(o.style.maxHeight=null,o.style.overflow="hidden")}});const i=document.createElement("style");i.textContent=".ac .ac-trigger::after { display: none !important; }",document.head.appendChild(i)});const d=document.querySelector(".header_menu_img"),l=document.querySelector(".modal_window");d.addEventListener("click",()=>{l.classList.toggle("active")});const u=document.querySelector(".x_icon");u.addEventListener("click",()=>{l.classList.toggle("active")});const m=document.querySelector(".nav_link");m.addEventListener("click",()=>{document.querySelector(".menu").classList.remove("active")});const p=document.querySelector(".menu_trigger");p.addEventListener("click",function(){document.querySelector(".menu").classList.toggle("active")});document.addEventListener("DOMContentLoaded",function(){const i=document.getElementById("reviews-list");function s(e){i.innerHTML="",e.forEach(t=>{const c=document.createElement("li");c.classList.add("swiper-slide","reviews-list-item"),c.innerHTML=`
                <img class="review-image" src="${t.avatar_url}" alt="${t.author}" width="48" height="48">
                <h3 class="reviews-names">${t.author}</h3>
                <p class="reviews-text">${t.review}</p>
            `,i.appendChild(c)}),requestAnimationFrame(o)}function o(){const e=document.querySelectorAll(".reviews-list-item");let t=0;e.forEach(c=>{c.style.height="auto",t=Math.max(t,c.offsetHeight)}),e.forEach(c=>{c.style.height=`${t}px`})}async function r(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!e.ok)throw new Error("Failed to fetch reviews");const t=await e.json();t&&Array.isArray(t)&&t.length>0?s(t):i.innerHTML='<li style="color: red;">Not found</li>'}catch(e){i.innerHTML='<li style="color: red;">Not found</li>',alert("reviews not found"),console.error("Reviews error:",e)}}function n(){const e=new a(".swiper",{speed:400,spaceBetween:16,slidesPerView:1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev",disabledClass:"swiper-button-disabled"},breakpoints:{768:{slidesPerView:2,speed:400,spaceBetween:16},1440:{slidesPerView:4,speed:400,spaceBetween:16}}});e.on("slideChange",function(){const t=e.navigation.prevEl,c=e.navigation.nextEl;t.disabled=e.isBeginning,c.disabled=e.isEnd})}r().then(()=>{n()})});const f="https://portfolio-js.b.goit.study/api/requests",g=document.querySelector(".form-subscribe"),h=document.querySelector(".model_overlay"),v=document.querySelector(".info_item");g.addEventListener("submit",y);function y(i){i.preventDefault();const s=i.target.elements.email.value,o=i.target.elements.comment.value;fetch(f,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:s,comment:o})}).then(r=>{if(!r.ok)throw new Error(r.statusText);return r.json()}).then(r=>console.log(r)).then(r=>v.insertAdjacentHTML("beforeend",w(r))).catch(r=>console.log(r.message))}function w(i){return h.classList.remove("visibility-hidden"),i.map(({title:s,message:o})=>`
        <div class="text_info">
        <p>${s}</p>
        </div>
        <div class="supporting_text">
        <p>${o}</p>
        </div>
    `).join("")}
//# sourceMappingURL=index.js.map
